### ISSUE TITLE
tried to register with an incorrect plugin identifier

### ISSUE THREAD

**Issue by malosaa** [petergerdes/homebridge-anna#2]
Hi

getting this issue now 

Plugin 'homebridge-anna' tried to register with an incorrect plugin identifier: 'homebridge-anna-thermostat'. Please report this to the developer!

any idea?

regards

**Comment by petergerdes** [comment]
Hi!

Since I don't use this plugin personally anymore, I'm not able to test it. I just pushed a possible fix. Would you be able to install it from Github and let me know if it works? Then I'll push to NPM!

Thanks!

**Comment by malosaa** [comment]
Hi thanks, it works and many thanks for the super fast reply and fix

now I need to get it working with my homebridge as I cant pair my homebridge.

**Comment by malosaa** [comment]
I did test it allone, but homebridge won't let me pair device.

if I use this it shows up in the log that's connected and updating, but when I want to pair device it fails, after when I just pair with no accessories I can pair.. dunno whats wrong
```
"accessories": 
	[
            {
               "accessory": "Thermostat",
               "name": "Thermostaat",
               "ip": "192.168.1XX",
               "password": "XXX",
               "maxTemp": "26",
               "minTemp": "15",
               "interval": "3000"
           }
       ],
```

**Comment by malosaa** [comment]
I did a complete new install of homebridge, deleted persist and other folders, and start the pair process, still no luck, but if I don't use your plugin and use other ones it pairs normally, perhaps something changed during the past moths

**Comment by malosaa** [comment]
i did get it to pair,

as I deleted this and it works 
  "maxTemp": "26",
               "minTemp": "15",

aswell there is an issue with the current temp,
instead of the current temp it shows the outside temperature.
because on the anna with the last update it shows you the outside temp via a station online.


regards

**Comment by petergerdes** [comment]
This plugin is made at the time of Anna v1.8. I'll update the documentation to reflect that. Don't know if someone else has the time and setup to continue development on this.

**Comment by malosaa** [comment]
@petergerdes 

wat if i send you my full xml output from anna core/appliances?
that would work to fix the issue, i am out of time to fix your code right now

regards
